pipeline{
    agent any
    tools{
        maven "maven"
    }
    stages{
        stage('git'){
            steps{
                checkout([$class: 'GitSCM', branches: [[name: '*/master']], extensions: [], userRemoteConfigs: [[credentialsId: '54825138-fbc2-4ddc-8321-418f5313fe9a', url: 'https://github.com/dilip16311/mavenrepo.git']]])
            }
        }
        stage('build'){
            steps{
                sh "mvn clean package"
            }
        }
        stage('build docker image'){
            steps{
                script{
                 sh "docker build . -t dilipkumar321/tomcatserver-1.${build_number}:latest"
                 sh "docker run -dit --name $containername -p 8000:8080 dilipkumar321/tomcatserver-1.${build_number}:latest"
                }
            }
        }
        stage('push docker image'){
            steps{
                script{
                    withCredentials([string(credentialsId: 'dilipkumar', variable: 'dockerhubpwd')]) {
                    sh "docker login -u dilipkumar321 -p ${dockerhubpwd}"
}
                    sh "docker push dilipkumar321/tomcatserver-1.${build_number}:latest"
                }
            }
        }
    }//stages ends
}//pipeline ends
